#ENC[AES256_GCM,data:vm2L4m5JhVUsAT0eSRSiVveEHnUZX0nIDfiKRLKzQjAH1D0PjWjKp1WJVvK4fJ8kAqgUY+mpJYNFZJ4TILyLdFvEe7o=,iv:4crzzNUbtQwskRgmRzXCasCHtjTdgmrxQdz/80aYlLg=,tag:UWwKr90yysg6C87BXlDIAQ==,type:comment]
model: ENC[AES256_GCM,data:G+ZoLlCn,iv:Zb7Y4Wbrbgwxd0aa+ooLht0EDgrkTEvWU7OwtFOl2Dw=,tag:8yWxsCDsYwq6cyeG76F7kA==,type:str]
clients:
    - type: ENC[AES256_GCM,data:BZ5+JkE+,iv:JWppsn8EFDItIJo5HlYj4DKUtg96ER5RcD6Ns1Bvnc8=,tag:MgkjVpNcGBM5WPvLfSmEJQ==,type:str]
      api_key: ENC[AES256_GCM,data:B4QbiC59CuskLtZJrL+cg2ei741WC7LE6BkwLy0Ug5sk/kNIJYpmSk+lQaDmJTYcrNZW,iv:w8H5sibEO3JxFvSbUyqDJ7hnLRrd9tZ6+nmEbqWXGRM=,tag:RrvvllIagwp0zFkz8n0YvQ==,type:str]
    - type: ENC[AES256_GCM,data:UWcNK4qe,iv:Hja8v6faJ+MGb6oPap7BAqEwIdeeVh1vx/uNUE5qgpA=,tag:I/kpET0Umc1xcb4eEJ5GvA==,type:str]
      api_key: ENC[AES256_GCM,data:i1J8HzIAJXxiSYH9fJHiWEHT+U0Dwe6+97lQeYZUg+repJNHOUPg,iv:yLnucZWkrWF0wYWaHPKJPBLV6PiGly1/CvFfCf1A/24=,tag:9197cdH40Y5TnmJdz5Ps+g==,type:str]
    - type: ENC[AES256_GCM,data:PlHPnF+q,iv:eWvvtl/CWKHX+HDMdgjZzbKxUxqjW0B0Z4w7ruZ5O6M=,tag:nhvb+/Ptb9E4WUVUSL9yzg==,type:str]
      api_key: ENC[AES256_GCM,data:zxpK7Mcipe889IJJ7bkRucYrA8QEYbXI6xsLTTQhpb7pWvX4ADegidwG9FzgzwBXyYQJICWX0GvZPwbdBiAbKmFu9tixZBNdxplGz0VFvitNqqemyb+pj2alEyZj/XZEPdCS5puY4gPMEWPs,iv:ES6SIh5/6YAl7GOUensCWGt55HfiAQo3F54JyS/0Gyo=,tag:n59ckuB+gTmVm8Yg71yeYQ==,type:str]
highlight: ENC[AES256_GCM,data:/2Q18g==,iv:pqKj8QKgv98d2q6PvBXDQBWJ/Bg30fiTQ0EXRNWc8yY=,tag:pYfSlHRdLg3r79smfRpK+w==,type:bool]
left_prompt: ENC[AES256_GCM,data:Pi2ruRCLzTGMxqtZyi0IfnsGAldgybqSUogD+gYe1SRTBz/QlCNMpgy4KdN9l4LSn2Wi74qEHEuk2+T6eiU1lJrtGITHuWtCrzr2JDYgHAaKdsJdbwpNrvkkuGjqG3eDwkcrtcbZ9JpRfdg78vPzmtlLzhNM7xBWbzFDrfmYOwcLtSQdfAaF1v7k0eu1++MS9BDTicitY1A5q99i,iv:3DRIsXYJmANIUh1fUiX7ZHPm3+GyKOkSEJAJidpJqac=,tag:AUcE/6QWdHhT7d/KxynhIg==,type:str]
right_prompt: ENC[AES256_GCM,data:IMOnhFeBzzpQt1Z4cjjqTc54LgAUKF6wUZU0G7R7/ZGhTDTbgFe6QQovMNMrg8wJcKflXcuZLa9pAcNil8UAEn8ExieTbpt1w1olKyQaq/DxINA/86mpsVqLG7R9xJE2dFh2Dc/sWWKUbwgXTBtQwvAQixN7tjXYoGsi8Acn,iv:7xBJTv3Q9BMf4YKd9wuResZeE4mOgCAaOzrNnt0+Wmk=,tag:0i1rg5zO3omCGPu75tfPhQ==,type:str]
stream: ENC[AES256_GCM,data:2flx6g==,iv:bpVkKVhWKZGEdriJVTK9GZ09Xner6Faxon7YGd+rtt0=,tag:8JXfb5nzv4Udf0eFt+o+aQ==,type:bool]
save: ENC[AES256_GCM,data:Ef/M4A==,iv:QYykizhKkC2Xru3AHkB2SaDkJiROX2j/oh7ceZ6BGuI=,tag:gm1Q1ZpAvFRnC7IzRfYOZQ==,type:bool]
save_session: null
summarize_prompt: ENC[AES256_GCM,data:7WCJh/BGWVMkEAKJk60lrD9y6q8phqQTUY3o2t7GF5FRdvYufUIiwVxXFXXd0ta7x+s1w4NWIaaHV8iJLYTN/uaTeTQoetvkm4tXaNh0ieotyF2cHd7PNg/AkPk=,iv:5YBxXhjz5W+sZx6XrS4cChZaXN5n28h9Vqola2QDSDw=,tag:0ESyn0MWftH3dXBUQRNT3w==,type:str]
summary_prompt: ENC[AES256_GCM,data:3s9RseKzuCsUPXFWrd0oWPX0ezZv4MSB0ZGisyCjl0Q9xPWNsOtiShw38IIvWaO/Eic=,iv:9EeemkPmhhSj5nNxE2824LFzmdfQz1/2zrYQ/kaoLic=,tag:wCh4j9IocFJ/ftuZFCdkwA==,type:str]
function_calling: ENC[AES256_GCM,data:QGo3rQ==,iv:9sTKiblFJfb5H/ZNqE2sLM7zKU/OVq/yRnKuOdXn6HA=,tag:oPyrWSsBTigEYSomeEOKtQ==,type:bool]
#ENC[AES256_GCM,data:kPc4BMPMilRis2WAQi5iRAc=,iv:oou46iwvw/SnApx+3QnP92b8KpTEiP/E7oMeabM2w2w=,tag:NpcgzlY574lhUGpvssvKjA==,type:comment]
use_tools: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zhxrt0yqdjqm3rtwuu850gyrw9yf7q2e0rw4tjzhjfxmxxqm0ecs3jej7q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcFg4YU1GdDZteDJNMXlL
            WXVjbkZkWUtscm9EWFl0Y2RrY0EyZEFmS0JJCjVFdWZmNEo4Tkh2MDdGUndwblMr
            Z0kxRlRIcWE2QUZzazJiUnA4Y1lYOGMKLS0tIGlldzN6YjVvSkdoWTZLWHpEWGRn
            dHBFWmR1VVlrT25udEFidElwK3EzSjAK0FsAEhbz/l8/nO2CQIM47BcmfwGmA/Zh
            dlakR6c63SuWmb1hNuvMc6clMs+uZzToJQi1qUnKa9B2ouynTKIYkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T19:14:45Z"
    mac: ENC[AES256_GCM,data:NHAuWSy5zr0cUHhcL8AiYwcJeZ1bv1A6HSku1s/ORUCe1j6Z9C6sTG/EBPtwV5Svtts2b/FiTVq1alCzaIUFsL1CX22N5LOuT6YmgCJTE3UDalW4Fv5t41Yd6QI6xHo2PcZeHqOAKMfoC8d5Wri634NEVGt/16azpk7eDoW+EoM=,iv:ew+L5LVieldkPPTQovOBB0IHmaoCRcCdzG8o0NeRqDM=,tag:PkGySV00WklZK1jteHXb7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
