#ENC[AES256_GCM,data:xqzBcNSZrqSCK9jFWce40ftBsxfDeFMhbnqSUPQxkk9YhErDzSuS4tw1VU2BTGE58nsBY/u4H4Z+GuxPHOnJaTR4E/I=,iv:hrdYe60nftEbFWqhlwqA0mnViXnSNiG6AmBpzr9qTvs=,tag:5ERqbOWzZ9Yuhe4jv007aQ==,type:comment]
model: ENC[AES256_GCM,data:+G/m0XYJ,iv:JuDL37bVKdarjMJgxNw51op9VzPlLwPW3wXOLFN3Syw=,tag:LO7MlG03nw/limIp2uj78Q==,type:str]
clients:
    - type: ENC[AES256_GCM,data:Gb3LwR0T,iv:0kP4u86nynkHcH0IkbiUlsPCyEo0yZ9okVJb5e4ztVU=,tag:lco0aRIFNzR5Iroa4SPf/A==,type:str]
      api_key: ENC[AES256_GCM,data:SzVplOSorYegBMxgV1R7JlParUCC8EskjSmoTrZLnHHkz+6uG/ABwaJau/ZWmZ5T7zPL,iv:3zClVkUeKQ1JDJuGOGW0Dxg2L8Sf+vzh+JuVr2qgpVc=,tag:GF2RbRdGRGwuBK1KxbyuPA==,type:str]
    - type: ENC[AES256_GCM,data:vqruY4j4,iv:eHjHD9MAYPwDp4m4QCWJwYPnQ6cQCmVk0LOgN4sFrHk=,tag:dPeX5fX0EbDxDkj7AcG/Ew==,type:str]
      api_key: ENC[AES256_GCM,data:r38/Dhrpv+piEIv0hOl+cFwFYXj4QlgOF8osOINLXee8d4E/bA0s,iv:unxfYVLVJEDDM1Wp87ijJJT2YInrwANYr3ZNjGmeCyE=,tag:Pu9iyISXmOJajqXzJ8LF9w==,type:str]
    - type: ENC[AES256_GCM,data:sHLhVie4,iv:saC8ADZ6qpJVBFlKTvJjTvrskHUTTGEbXa7XUgl78qo=,tag:Ups6KqJiXVvJtI1laSqFUA==,type:str]
      api_key: ENC[AES256_GCM,data:Hlin7xG4G/GqSfWyFuuLPD71VhEPIiRc2RLJJJVjqqNKOE9IUX0kr2ojPfKnhKaoKcOlI/88tWl9ZHoIX/2cyfS0SPYfz87GzjlzZkcG8ws/jIyK1f811i95LLLq8xVhbL9u0DVGas9AcY5S,iv:wh0mkkKTTTy/QqDEPBpCGYW3/gyq20PFhBDO9RYMQ5E=,tag:UCsx6RKBH7yOO/B9Zy8tXg==,type:str]
highlight: ENC[AES256_GCM,data:fYU1RA==,iv:Bw11iohQSPAsklPH/SL6c5ak7k/34WJbTV1UTfLoSZA=,tag:XiHSl1Hd7uXMRFECJR0VKA==,type:bool]
left_prompt: ENC[AES256_GCM,data:MvASQAgu2e5RxSCL7S+T0eVPDsQPBaQcE4HkpQ8gp4VpK4QORtCbXKQgjh/QE9P0NYgUsCQI+GUtOpqcrvHejubTqaEkoJudX2jBKHOAjBXwNe9qJQBil4KisT0HdweNy8Bsxz71oZ6z/ko55Tp1NyWXILDBMFiMmUXphGG0vTYAbrhDKi9z7ywOF2cSNl5UT2UFVstKBYBphqxB,iv:dh36AvVyeTWwzQO+sG7Q7b/wymFWWl1oxjJ4dRCITsE=,tag:XYBym/8HCHxmJaNCCknI8Q==,type:str]
right_prompt: ENC[AES256_GCM,data:sp6HeB5xBTy4a8tHvLPSKIr5ReIdG+xj95SHw9RIMzQl7QNcX6gezHIVUUabnbzU62tkiLdvo2OwGdwZtJttqYAyt3r6uQzhHXYLPA7oHnpvREgKIQOjcOITe/C5e7mCs0ft/n3M+JjhthzlXfWPf5zyXJC1aJsSy+fl5xyF,iv:2M094pIj8u2+wbRmPSmKExngSxZu3q8LR67RH5RTtKg=,tag:RYteKWZlgzMAGNdxvW+aUg==,type:str]
stream: ENC[AES256_GCM,data:NkA1qQ==,iv:GqjSKjfMEumOfI/Oy5Aut/7DQ/dqV2W4O8D82X4GETU=,tag:s430v2svvZUESQmWIj8Nkw==,type:bool]
save: ENC[AES256_GCM,data:orKqyw==,iv:za/1h2t8zc886LG9lX4NVFIQ/+v+AM0ZHEVR8++2Vr4=,tag:iYeuNbOBcWHrEnsE0g/OvA==,type:bool]
save_session: null
summarize_prompt: ENC[AES256_GCM,data:OWdD6eI7Zz17ae1qkOVKvvxR0FWFo4H7WCNfOfpstl145Xw8Kk+sVJU6gFNJU4bnwBu3/6/ADAO8ikRbmn+zSIG/o03u+urFYJdRTDydu7j0pZF7o8l14WtWq+w=,iv:mnpaWW3jqU5qeRtCR5aNAJznpo9EpO8u6+wcFcsdR78=,tag:iJfRIwozqM117Np1BekaRA==,type:str]
summary_prompt: ENC[AES256_GCM,data:EaARwpLMOOBrK5z/YKBFBi9X3PJcErhP0bx+LDZ6HDX7s5wa0OopBO9d1NFh4zWXhEI=,iv:6o36jhHKOWIC39kDB+fBD4HACJbKvUTTw6cMfdcHo5E=,tag:yAPgwGt3GL5ZhRjipcEWyA==,type:str]
function_calling: ENC[AES256_GCM,data:PUGarQ==,iv:1NjhosiIKABXOwSMVVQvsIdmoIUUlbgvfON4YLpSOPE=,tag:gI0BLM1GOlqK7CdX9hJsbA==,type:bool]
#ENC[AES256_GCM,data:cK8pcrGLP75kLgICiN0oPRw=,iv:hq7aDqhzSULb1woVYutFWdzgF9hi+NRpknNINnVQQFM=,tag:G86OCxqmcwr3UgrIZjIAYw==,type:comment]
use_tools: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zhxrt0yqdjqm3rtwuu850gyrw9yf7q2e0rw4tjzhjfxmxxqm0ecs3jej7q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaTR3enNsZU5VQ21tZmFq
            M2xYdnFGaDR0bGgwKzhVMTZScitGeERDdXk0CklwbCtQR0Y3SE80emhlOE9TWTZk
            Q2xXNkhnR1NZMTFzZCtaOENIc05qZG8KLS0tIC90VzRCb2tVb3A0ZGlEWUJJZCtQ
            SFdjLzhSd2Nrb2FUL2ZFU3pUeG9SRW8K87gPSg1YTQL0hWH9LDPVdDXZlexoDRSM
            yHOW/cwVD0P407KYCQ24WQe7LKtTaqt9caTSgR2YZ272To7dXKvLbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T19:10:19Z"
    mac: ENC[AES256_GCM,data:sdPqA1zrySjRvYPB+kQnE7nNZDMy9IAuyI60BbIuJ3yPz5MF/e7Eii2koN6XYKjZEvCQIN0Hlo4xxdnHleZfEHLr+Anq6Dn/Xfv+5zOs2Tiskkl/3py3XkOQnu7tov/TjdIb7X4sI6qp816QEEUaPCAfPWcMwhouq3F0Oqw9CcI=,iv:MSwx91392i0ROSLq+vSpxlGGwcA4ukE5eES3nyE5pz4=,tag:2VqiUmjDojEBA/QeeiUIQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
